<?php

namespace App\Support\Tables;

class EventTableColumns
{
    public static function columns(): array
    {
        return [
            [
                'field_name' => 'id',
                'label' => 'ID',
                'placeholder' => null,
                'cast_type' => 'integer',
                'input_type' => 'number',
                'filterable' => false,
                'sortable' => true,
                'default_sort' => 'desc',
            ],
            [
                'field_name' => 'title',
                'label' => 'Titolo',
                'placeholder' => 'Cerca per titolo',
                'cast_type' => 'string',
                'input_type' => 'text',
                'filterable' => true,
                'sortable' => true,
                'default_sort' => null,
            ],
            [
                'field_name' => 'category.name',
                'label' => 'Categoria',
                'placeholder' => 'Categoria',
                'cast_type' => 'string',
                'input_type' => 'select',
                'filterable' => true,
                'sortable' => true,
                'default_sort' => null,
            ],
            [
                'field_name' => 'location',
                'label' => 'Luogo',
                'placeholder' => 'Cerca luogo',
                'cast_type' => 'string',
                'input_type' => 'text',
                'filterable' => true,
                'sortable' => true,
                'default_sort' => null,
            ],
            [
                'field_name' => 'venueType.name',
                'label' => 'Tipologia luogo',
                'placeholder' => 'Tipologia luogo',
                'cast_type' => 'string',
                'input_type' => 'select',
                'filterable' => true,
                'sortable' => true,
                'default_sort' => null,
            ],
            [
                'field_name' => 'available_tickets',
                'label' => 'Biglietti disponibili',
                'placeholder' => 'Numero',
                'cast_type' => 'integer',
                'input_type' => 'number',
                'filterable' => false,
                'sortable' => false,
                'default_sort' => null,
            ],
            [
                'field_name' => 'starts_at',
                'label' => 'Data inizio',
                'placeholder' => 'Data inizio',
                'cast_type' => 'datetime',
                'input_type' => 'datetime-local',
                'filterable' => true,
                'sortable' => true,
                'default_sort' => 'asc',
            ],
            [
                'field_name' => 'ends_at',
                'label' => 'Data fine',
                'placeholder' => 'Data fine',
                'cast_type' => 'datetime',
                'input_type' => 'datetime-local',
                'filterable' => true,
                'sortable' => true,
                'default_sort' => null,
            ],
            [
                'field_name' => 'sale_starts_at',
                'label' => 'Vendita da',
                'placeholder' => 'Data vendita',
                'cast_type' => 'datetime',
                'input_type' => 'datetime-local',
                'filterable' => true,
                'sortable' => true,
                'default_sort' => null,
            ],
            [
                'field_name' => 'image_url',
                'label' => 'URL immagine',
                'placeholder' => null,
                'cast_type' => 'string',
                'input_type' => 'text',
                'filterable' => false,
                'sortable' => false,
                'default_sort' => null,
            ],
            [
                'field_name' => 'is_featured',
                'label' => 'In evidenza',
                'placeholder' => null,
                'cast_type' => 'boolean',
                'input_type' => 'checkbox',
                'filterable' => true,
                'sortable' => true,
                'default_sort' => null,
            ],
            [
                'field_name' => 'queue_enabled',
                'label' => 'Coda attiva',
                'placeholder' => null,
                'cast_type' => 'boolean',
                'input_type' => 'checkbox',
                'filterable' => true,
                'sortable' => true,
                'default_sort' => null,
            ],
            [
                'field_name' => 'queue_entries_count',
                'label' => 'N. code attive',
                'placeholder' => 'Minuti',
                'cast_type' => 'integer',
                'input_type' => 'number',
                'filterable' => false,
                'sortable' => true,
                'default_sort' => null,
            ],
        ];
    }
}
